CREATE DATABASE DailyPlannerDB;
GO

USE DailyPlannerDB;

CREATE TABLE Notes (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    NoteDate DATETIME NOT NULL,
    NoteText NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);